<?php exit(0)?>
<fndatabase>
	<fnc_products>
		<unirecid>3</unirecid>
		<name>Microsoft IntelliMouse Pro</name>
		<status>1</status>
		<model>MSIMPRO</model>
		<sort_order></sort_order>
		<description>Every element of IntelliMouse Pro - from its unique arched shape to the texture of the rubber grip around its base - is the product of extensive customer and ergonomic research. Microsoft&#039;s popular wheel control, which now allows zooming and universal scrolling functions, gives IntelliMouse Pro outstanding comfort and efficiency.</description>
		<photo1>msimpro.gif</photo1>
		<photo2></photo2>
		<photo3></photo3>
		<photo4></photo4>
		<photo5></photo5>
		<photo6></photo6>
		<attachment></attachment>
		<attachment2></attachment2>
		<height></height>
		<width></width>
		<depth></depth>
		<year></year>
		<weight>7.00</weight>
		<manufacturers>3</manufacturers>
		<freeshipping></freeshipping>
		<quantity>2</quantity>
		<price>49.9900</price>
		<vat></vat>
		<name_it></name_it>
		<description_it></description_it>
		<name_en></name_en>
		<description_en></description_en>
		<name_de></name_de>
		<name_es></name_es>
		<description_de></description_de>
		<description_es></description_es>
		<name_fr></name_fr>
		<description_fr></description_fr>
	</fnc_products>
</fndatabase>