<?php exit(0)?>
<fndatabase>
	<fnc_products>
		<unirecid>4</unirecid>
		<name>The Replacement Killers</name>
		<status>1</status>
		<model>DVD-RPMK</model>
		<sort_order></sort_order>
		<description>Regional Code: 2 (Japan, Europe, Middle East, South Africa).&lt;br&gt;Languages: English, Deutsch.&lt;br&gt;Subtitles: English, Deutsch, Spanish.&lt;br&gt;Audio: Dolby Surround 5.1.&lt;br&gt;Picture Format: 16:9 Wide-Screen.&lt;br&gt;Length: (approx) 80 minutes.&lt;br&gt;Other: Interactive Menus, Chapter Selection, Subtitles (more languages).</description>
		<photo1>replacement_killers.gif</photo1>
		<photo2></photo2>
		<photo3></photo3>
		<photo4></photo4>
		<photo5></photo5>
		<photo6></photo6>
		<attachment></attachment>
		<attachment2></attachment2>
		<height></height>
		<width></width>
		<depth></depth>
		<year></year>
		<weight>23.00</weight>
		<manufacturers>2</manufacturers>
		<freeshipping></freeshipping>
		<quantity>13</quantity>
		<price>42.0000</price>
		<vat></vat>
		<name_it></name_it>
		<description_it></description_it>
		<name_en></name_en>
		<description_en></description_en>
		<name_de></name_de>
		<name_es></name_es>
		<description_de></description_de>
		<description_es></description_es>
		<name_fr></name_fr>
		<description_fr></description_fr>
	</fnc_products>
</fndatabase>