<?php exit(0)?>
<fndatabase>
	<fnc_products>
		<unirecid>22</unirecid>
		<name>Unreal Tournament</name>
		<status>1</status>
		<model>PC-UNTM</model>
		<sort_order></sort_order>
		<description>From the creators of the best-selling Unreal, comes Unreal Tournament. A new kind of single player experience. A ruthless multiplayer revolution.&lt;br&gt;&lt;br&gt;This stand-alone game showcases completely new team-based gameplay, groundbreaking multi-faceted single player action or dynamic multi-player mayhem. It&#039;s a fight to the finish for the title of Unreal Grand Master in the gladiatorial arena. A single player experience like no other! Guide your team of &#039;bots&#039; (virtual teamates) against the hardest criminals in the galaxy for the ultimate title - the Unreal Grand Master.</description>
		<photo1>unreal_tournament.gif</photo1>
		<photo2></photo2>
		<photo3></photo3>
		<photo4></photo4>
		<photo5></photo5>
		<photo6></photo6>
		<attachment></attachment>
		<attachment2></attachment2>
		<height></height>
		<width></width>
		<depth></depth>
		<year></year>
		<weight>7.00</weight>
		<manufacturers>8</manufacturers>
		<freeshipping></freeshipping>
		<quantity>13</quantity>
		<price>89.9900</price>
		<vat></vat>
		<name_it></name_it>
		<description_it></description_it>
		<name_en></name_en>
		<description_en></description_en>
		<name_de></name_de>
		<name_es></name_es>
		<description_de></description_de>
		<description_es></description_es>
		<name_fr></name_fr>
		<description_fr></description_fr>
	</fnc_products>
</fndatabase>