<?exit(0);?>
<tables>
	<field>
		<name>unirecid</name>
		<primarykey>1</primarykey>
		<frm_show>0</frm_show>
		<extra>autoincrement</extra>		
	</field>
	<field>
		<name>country</name>
		<foreignkey>fnc_countries</foreignkey>
		<fk_link_field>unirecid</fk_link_field>
		<fk_show_field>name</fk_show_field>
		<frm_required>1</frm_required>
	</field>
	<field>
		<name>code</name>
		<type>string</type>
	</field>
	<field>
		<name>name</name>
		<type>string</type>
	</field>
	<indexfield>country</indexfield>
</tables>
