<?php exit(0);?>
<tables>
	<field>
		<name>unirecid</name>
		<extra>autoincrement</extra>
		<frm_show>0</frm_show>
		<primarykey>1</primarykey>
	</field>
	<field>
		<name>country</name>
		<frm_i18n>country</frm_i18n>
		<foreignkey>fnc_countries</foreignkey>
		<fk_link_field>unirecid</fk_link_field>
		<fk_show_field>name</fk_show_field>
	</field>
	<field>
		<name>zone</name>
		<frm_i18n>zone</frm_i18n>
		<foreignkey>fnc_zones</foreignkey>
		<fk_link_field>unirecid</fk_link_field>
		<fk_show_field>name</fk_show_field>
	</field>
	<field>
		<name>tablename</name>
		<frm_i18n>table</frm_i18n>
		<frm_type>select</frm_type>
	</field>
<filename>shippingcostszones</filename>
</tables>