<?php exit(0);?>
<fndatabase>
	<fnc_zones>
		<unirecid>95</unirecid>
		<country>14</country>
		<code>WI</code>
		<name>Wien</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>96</unirecid>
		<country>14</country>
		<code>NO</code>
		<name>Nieder&ouml;sterreich</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>97</unirecid>
		<country>14</country>
		<code>OO</code>
		<name>Ober&ouml;sterreich</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>98</unirecid>
		<country>14</country>
		<code>SB</code>
		<name>Salzburg</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>99</unirecid>
		<country>14</country>
		<code>KN</code>
		<name>K&auml;rnten</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>100</unirecid>
		<country>14</country>
		<code>ST</code>
		<name>Steiermark</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>101</unirecid>
		<country>14</country>
		<code>TI</code>
		<name>Tirol</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>102</unirecid>
		<country>14</country>
		<code>BL</code>
		<name>Burgenland</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>103</unirecid>
		<country>14</country>
		<code>VB</code>
		<name>Voralberg</name>
	</fnc_zones>
</fndatabase>