<?php exit(0);?>
<fndatabase>
	<fnc_zones>
		<unirecid>104</unirecid>
		<country>204</country>
		<code>AG</code>
		<name>Aargau</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>105</unirecid>
		<country>204</country>
		<code>AI</code>
		<name>Appenzell Innerrhoden</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>106</unirecid>
		<country>204</country>
		<code>AR</code>
		<name>Appenzell Ausserrhoden</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>107</unirecid>
		<country>204</country>
		<code>BE</code>
		<name>Bern</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>108</unirecid>
		<country>204</country>
		<code>BL</code>
		<name>Basel-Landschaft</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>109</unirecid>
		<country>204</country>
		<code>BS</code>
		<name>Basel-Stadt</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>110</unirecid>
		<country>204</country>
		<code>FR</code>
		<name>Freiburg</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>111</unirecid>
		<country>204</country>
		<code>GE</code>
		<name>Genf</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>112</unirecid>
		<country>204</country>
		<code>GL</code>
		<name>Glarus</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>113</unirecid>
		<country>204</country>
		<code>JU</code>
		<name>Graub&uuml;nden</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>114</unirecid>
		<country>204</country>
		<code>JU</code>
		<name>Jura</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>115</unirecid>
		<country>204</country>
		<code>LU</code>
		<name>Luzern</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>116</unirecid>
		<country>204</country>
		<code>NE</code>
		<name>Neuenburg</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>117</unirecid>
		<country>204</country>
		<code>NW</code>
		<name>Nidwalden</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>118</unirecid>
		<country>204</country>
		<code>OW</code>
		<name>Obwalden</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>119</unirecid>
		<country>204</country>
		<code>SG</code>
		<name>St. Gallen</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>120</unirecid>
		<country>204</country>
		<code>SH</code>
		<name>Schaffhausen</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>121</unirecid>
		<country>204</country>
		<code>SO</code>
		<name>Solothurn</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>122</unirecid>
		<country>204</country>
		<code>SZ</code>
		<name>Schwyz</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>123</unirecid>
		<country>204</country>
		<code>TG</code>
		<name>Thurgau</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>124</unirecid>
		<country>204</country>
		<code>TI</code>
		<name>Tessin</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>125</unirecid>
		<country>204</country>
		<code>UR</code>
		<name>Uri</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>126</unirecid>
		<country>204</country>
		<code>VD</code>
		<name>Waadt</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>127</unirecid>
		<country>204</country>
		<code>VS</code>
		<name>Wallis</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>128</unirecid>
		<country>204</country>
		<code>ZG</code>
		<name>Zug</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>129</unirecid>
		<country>204</country>
		<code>ZH</code>
		<name>Z&uuml;rich</name>
	</fnc_zones>
</fndatabase>