<?php exit(0);?>
<fndatabase>
	<fnc_zones>
		<unirecid>1</unirecid>
		<country>223</country>
		<code>AL</code>
		<name>Alabama</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>2</unirecid>
		<country>223</country>
		<code>AK</code>
		<name>Alaska</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>3</unirecid>
		<country>223</country>
		<code>AS</code>
		<name>American Samoa</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>4</unirecid>
		<country>223</country>
		<code>AZ</code>
		<name>Arizona</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>5</unirecid>
		<country>223</country>
		<code>AR</code>
		<name>Arkansas</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>6</unirecid>
		<country>223</country>
		<code>AF</code>
		<name>Armed Forces Africa</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>7</unirecid>
		<country>223</country>
		<code>AA</code>
		<name>Armed Forces Americas</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>8</unirecid>
		<country>223</country>
		<code>AC</code>
		<name>Armed Forces Canada</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>9</unirecid>
		<country>223</country>
		<code>AE</code>
		<name>Armed Forces Europe</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>10</unirecid>
		<country>223</country>
		<code>AM</code>
		<name>Armed Forces Middle East</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>11</unirecid>
		<country>223</country>
		<code>AP</code>
		<name>Armed Forces Pacific</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>12</unirecid>
		<country>223</country>
		<code>CA</code>
		<name>California</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>13</unirecid>
		<country>223</country>
		<code>CO</code>
		<name>Colorado</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>14</unirecid>
		<country>223</country>
		<code>CT</code>
		<name>Connecticut</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>15</unirecid>
		<country>223</country>
		<code>DE</code>
		<name>Delaware</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>16</unirecid>
		<country>223</country>
		<code>DC</code>
		<name>District of Columbia</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>17</unirecid>
		<country>223</country>
		<code>FM</code>
		<name>Federated States Of Micronesia</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>18</unirecid>
		<country>223</country>
		<code>FL</code>
		<name>Florida</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>19</unirecid>
		<country>223</country>
		<code>GA</code>
		<name>Georgia</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>20</unirecid>
		<country>223</country>
		<code>GU</code>
		<name>Guam</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>21</unirecid>
		<country>223</country>
		<code>HI</code>
		<name>Hawaii</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>22</unirecid>
		<country>223</country>
		<code>ID</code>
		<name>Idaho</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>23</unirecid>
		<country>223</country>
		<code>IL</code>
		<name>Illinois</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>24</unirecid>
		<country>223</country>
		<code>IN</code>
		<name>Indiana</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>25</unirecid>
		<country>223</country>
		<code>IA</code>
		<name>Iowa</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>26</unirecid>
		<country>223</country>
		<code>KS</code>
		<name>Kansas</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>27</unirecid>
		<country>223</country>
		<code>KY</code>
		<name>Kentucky</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>28</unirecid>
		<country>223</country>
		<code>LA</code>
		<name>Louisiana</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>29</unirecid>
		<country>223</country>
		<code>ME</code>
		<name>Maine</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>30</unirecid>
		<country>223</country>
		<code>MH</code>
		<name>Marshall Islands</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>31</unirecid>
		<country>223</country>
		<code>MD</code>
		<name>Maryland</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>32</unirecid>
		<country>223</country>
		<code>MA</code>
		<name>Massachusetts</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>33</unirecid>
		<country>223</country>
		<code>MI</code>
		<name>Michigan</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>34</unirecid>
		<country>223</country>
		<code>MN</code>
		<name>Minnesota</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>35</unirecid>
		<country>223</country>
		<code>MS</code>
		<name>Mississippi</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>36</unirecid>
		<country>223</country>
		<code>MO</code>
		<name>Missouri</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>37</unirecid>
		<country>223</country>
		<code>MT</code>
		<name>Montana</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>38</unirecid>
		<country>223</country>
		<code>NE</code>
		<name>Nebraska</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>39</unirecid>
		<country>223</country>
		<code>NV</code>
		<name>Nevada</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>40</unirecid>
		<country>223</country>
		<code>NH</code>
		<name>New Hampshire</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>41</unirecid>
		<country>223</country>
		<code>NJ</code>
		<name>New Jersey</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>42</unirecid>
		<country>223</country>
		<code>NM</code>
		<name>New Mexico</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>43</unirecid>
		<country>223</country>
		<code>NY</code>
		<name>New York</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>44</unirecid>
		<country>223</country>
		<code>NC</code>
		<name>North Carolina</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>45</unirecid>
		<country>223</country>
		<code>ND</code>
		<name>North Dakota</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>46</unirecid>
		<country>223</country>
		<code>MP</code>
		<name>Northern Mariana Islands</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>47</unirecid>
		<country>223</country>
		<code>OH</code>
		<name>Ohio</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>48</unirecid>
		<country>223</country>
		<code>OK</code>
		<name>Oklahoma</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>49</unirecid>
		<country>223</country>
		<code>OR</code>
		<name>Oregon</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>50</unirecid>
		<country>223</country>
		<code>PW</code>
		<name>Palau</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>51</unirecid>
		<country>223</country>
		<code>PA</code>
		<name>Pennsylvania</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>52</unirecid>
		<country>223</country>
		<code>PR</code>
		<name>Puerto Rico</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>53</unirecid>
		<country>223</country>
		<code>RI</code>
		<name>Rhode Island</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>54</unirecid>
		<country>223</country>
		<code>SC</code>
		<name>South Carolina</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>55</unirecid>
		<country>223</country>
		<code>SD</code>
		<name>South Dakota</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>56</unirecid>
		<country>223</country>
		<code>TN</code>
		<name>Tennessee</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>57</unirecid>
		<country>223</country>
		<code>TX</code>
		<name>Texas</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>58</unirecid>
		<country>223</country>
		<code>UT</code>
		<name>Utah</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>59</unirecid>
		<country>223</country>
		<code>VT</code>
		<name>Vermont</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>60</unirecid>
		<country>223</country>
		<code>VI</code>
		<name>Virgin Islands</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>61</unirecid>
		<country>223</country>
		<code>VA</code>
		<name>Virginia</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>62</unirecid>
		<country>223</country>
		<code>WA</code>
		<name>Washington</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>63</unirecid>
		<country>223</country>
		<code>WV</code>
		<name>West Virginia</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>64</unirecid>
		<country>223</country>
		<code>WI</code>
		<name>Wisconsin</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>65</unirecid>
		<country>223</country>
		<code>WY</code>
		<name>Wyoming</name>
	</fnc_zones>
</fndatabase>