<?xml version="1.0" encoding="UTF-8"?>
<?php exit(0);?>
<fndatabase>
	<fnc_countries>
		<unirecid>1</unirecid>
		<iso_code_2>AF</iso_code_2>
		<iso_code_3>AFG</iso_code_3>
		<name>Afghanistan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>2</unirecid>
		<iso_code_2>AL</iso_code_2>
		<iso_code_3>ALB</iso_code_3>
		<name>Albania</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>3</unirecid>
		<iso_code_2>DZ</iso_code_2>
		<iso_code_3>DZA</iso_code_3>
		<name>Algeria</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>4</unirecid>
		<iso_code_2>AS</iso_code_2>
		<iso_code_3>ASM</iso_code_3>
		<name>American Samoa</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>5</unirecid>
		<iso_code_2>AD</iso_code_2>
		<iso_code_3>AND</iso_code_3>
		<name>Andorra</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>6</unirecid>
		<iso_code_2>AO</iso_code_2>
		<iso_code_3>AGO</iso_code_3>
		<name>Angola</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>7</unirecid>
		<iso_code_2>AI</iso_code_2>
		<iso_code_3>AIA</iso_code_3>
		<name>Anguilla</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>8</unirecid>
		<iso_code_2>AQ</iso_code_2>
		<iso_code_3>ATA</iso_code_3>
		<name>Antarctica</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>9</unirecid>
		<iso_code_2>AG</iso_code_2>
		<iso_code_3>ATG</iso_code_3>
		<name>Antigua and Barbuda</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>10</unirecid>
		<iso_code_2>AR</iso_code_2>
		<iso_code_3>ARG</iso_code_3>
		<name>Argentina</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>11</unirecid>
		<iso_code_2>AM</iso_code_2>
		<iso_code_3>ARM</iso_code_3>
		<name>Armenia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>12</unirecid>
		<iso_code_2>AW</iso_code_2>
		<iso_code_3>ABW</iso_code_3>
		<name>Aruba</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>13</unirecid>
		<iso_code_2>AU</iso_code_2>
		<iso_code_3>AUS</iso_code_3>
		<name>Australia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>14</unirecid>
		<iso_code_2>AT</iso_code_2>
		<iso_code_3>AUT</iso_code_3>
		<name>Austria</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>15</unirecid>
		<iso_code_2>AZ</iso_code_2>
		<iso_code_3>AZE</iso_code_3>
		<name>Azerbaijan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>16</unirecid>
		<iso_code_2>BS</iso_code_2>
		<iso_code_3>BHS</iso_code_3>
		<name>Bahamas</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>17</unirecid>
		<iso_code_2>BH</iso_code_2>
		<iso_code_3>BHR</iso_code_3>
		<name>Bahrain</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>18</unirecid>
		<iso_code_2>BD</iso_code_2>
		<iso_code_3>BGD</iso_code_3>
		<name>Bangladesh</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>19</unirecid>
		<iso_code_2>BB</iso_code_2>
		<iso_code_3>BRB</iso_code_3>
		<name>Barbados</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>20</unirecid>
		<iso_code_2>BY</iso_code_2>
		<iso_code_3>BLR</iso_code_3>
		<name>Belarus</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>21</unirecid>
		<iso_code_2>BE</iso_code_2>
		<iso_code_3>BEL</iso_code_3>
		<name>Belgium</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>22</unirecid>
		<iso_code_2>BZ</iso_code_2>
		<iso_code_3>BLZ</iso_code_3>
		<name>Belize</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>23</unirecid>
		<iso_code_2>BJ</iso_code_2>
		<iso_code_3>BEN</iso_code_3>
		<name>Benin</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>24</unirecid>
		<iso_code_2>BM</iso_code_2>
		<iso_code_3>BMU</iso_code_3>
		<name>Bermuda</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>25</unirecid>
		<iso_code_2>BT</iso_code_2>
		<iso_code_3>BTN</iso_code_3>
		<name>Bhutan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>26</unirecid>
		<iso_code_2>BO</iso_code_2>
		<iso_code_3>BOL</iso_code_3>
		<name>Bolivia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>27</unirecid>
		<iso_code_2>BA</iso_code_2>
		<iso_code_3>BIH</iso_code_3>
		<name>Bosnia and Herzegowina</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>28</unirecid>
		<iso_code_2>BW</iso_code_2>
		<iso_code_3>BWA</iso_code_3>
		<name>Botswana</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>29</unirecid>
		<iso_code_2>BV</iso_code_2>
		<iso_code_3>BVT</iso_code_3>
		<name>Bouvet Island</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>30</unirecid>
		<iso_code_2>BR</iso_code_2>
		<iso_code_3>BRA</iso_code_3>
		<name>Brazil</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>31</unirecid>
		<iso_code_2>IO</iso_code_2>
		<iso_code_3>IOT</iso_code_3>
		<name>British Indian Ocean Territory</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>32</unirecid>
		<iso_code_2>BN</iso_code_2>
		<iso_code_3>BRN</iso_code_3>
		<name>Brunei Darussalam</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>33</unirecid>
		<iso_code_2>BG</iso_code_2>
		<iso_code_3>BGR</iso_code_3>
		<name>Bulgaria</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>34</unirecid>
		<iso_code_2>BF</iso_code_2>
		<iso_code_3>BFA</iso_code_3>
		<name>Burkina Faso</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>35</unirecid>
		<iso_code_2>BI</iso_code_2>
		<iso_code_3>BDI</iso_code_3>
		<name>Burundi</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>36</unirecid>
		<iso_code_2>KH</iso_code_2>
		<iso_code_3>KHM</iso_code_3>
		<name>Cambodia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>37</unirecid>
		<iso_code_2>CM</iso_code_2>
		<iso_code_3>CMR</iso_code_3>
		<name>Cameroon</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>38</unirecid>
		<iso_code_2>CA</iso_code_2>
		<iso_code_3>CAN</iso_code_3>
		<name>Canada</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>39</unirecid>
		<iso_code_2>CV</iso_code_2>
		<iso_code_3>CPV</iso_code_3>
		<name>Cape Verde</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>40</unirecid>
		<iso_code_2>KY</iso_code_2>
		<iso_code_3>CYM</iso_code_3>
		<name>Cayman Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>41</unirecid>
		<iso_code_2>CF</iso_code_2>
		<iso_code_3>CAF</iso_code_3>
		<name>Central African Republic</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>42</unirecid>
		<iso_code_2>TD</iso_code_2>
		<iso_code_3>TCD</iso_code_3>
		<name>Chad</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>43</unirecid>
		<iso_code_2>CL</iso_code_2>
		<iso_code_3>CHL</iso_code_3>
		<name>Chile</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>44</unirecid>
		<iso_code_2>CN</iso_code_2>
		<iso_code_3>CHN</iso_code_3>
		<name>China</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>45</unirecid>
		<iso_code_2>CX</iso_code_2>
		<iso_code_3>CXR</iso_code_3>
		<name>Christmas Island</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>46</unirecid>
		<iso_code_2>CC</iso_code_2>
		<iso_code_3>CCK</iso_code_3>
		<name>Cocos (Keeling) Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>47</unirecid>
		<iso_code_2>CO</iso_code_2>
		<iso_code_3>COL</iso_code_3>
		<name>Colombia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>48</unirecid>
		<iso_code_2>KM</iso_code_2>
		<iso_code_3>COM</iso_code_3>
		<name>Comoros</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>49</unirecid>
		<iso_code_2>CG</iso_code_2>
		<iso_code_3>COG</iso_code_3>
		<name>Congo</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>50</unirecid>
		<iso_code_2>CK</iso_code_2>
		<iso_code_3>COK</iso_code_3>
		<name>Cook Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>51</unirecid>
		<iso_code_2>CR</iso_code_2>
		<iso_code_3>CRI</iso_code_3>
		<name>Costa Rica</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>52</unirecid>
		<iso_code_2>CI</iso_code_2>
		<iso_code_3>CIV</iso_code_3>
		<name>Cote D&#039;Ivoire</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>53</unirecid>
		<iso_code_2>HR</iso_code_2>
		<iso_code_3>HRV</iso_code_3>
		<name>Croatia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>54</unirecid>
		<iso_code_2>CU</iso_code_2>
		<iso_code_3>CUB</iso_code_3>
		<name>Cuba</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>55</unirecid>
		<iso_code_2>CY</iso_code_2>
		<iso_code_3>CYP</iso_code_3>
		<name>Cyprus</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>56</unirecid>
		<iso_code_2>CZ</iso_code_2>
		<iso_code_3>CZE</iso_code_3>
		<name>Czech Republic</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>57</unirecid>
		<iso_code_2>DK</iso_code_2>
		<iso_code_3>DNK</iso_code_3>
		<name>Denmark</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>58</unirecid>
		<iso_code_2>DJ</iso_code_2>
		<iso_code_3>DJI</iso_code_3>
		<name>Djibouti</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>59</unirecid>
		<iso_code_2>DM</iso_code_2>
		<iso_code_3>DMA</iso_code_3>
		<name>Dominica</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>60</unirecid>
		<iso_code_2>DO</iso_code_2>
		<iso_code_3>DOM</iso_code_3>
		<name>Dominican Republic</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>61</unirecid>
		<iso_code_2>TP</iso_code_2>
		<iso_code_3>TMP</iso_code_3>
		<name>East Timor</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>62</unirecid>
		<iso_code_2>EC</iso_code_2>
		<iso_code_3>ECU</iso_code_3>
		<name>Ecuador</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>63</unirecid>
		<iso_code_2>EG</iso_code_2>
		<iso_code_3>EGY</iso_code_3>
		<name>Egypt</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>64</unirecid>
		<iso_code_2>SV</iso_code_2>
		<iso_code_3>SLV</iso_code_3>
		<name>El Salvador</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>65</unirecid>
		<iso_code_2>GQ</iso_code_2>
		<iso_code_3>GNQ</iso_code_3>
		<name>Equatorial Guinea</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>66</unirecid>
		<iso_code_2>ER</iso_code_2>
		<iso_code_3>ERI</iso_code_3>
		<name>Eritrea</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>67</unirecid>
		<iso_code_2>EE</iso_code_2>
		<iso_code_3>EST</iso_code_3>
		<name>Estonia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>68</unirecid>
		<iso_code_2>ET</iso_code_2>
		<iso_code_3>ETH</iso_code_3>
		<name>Ethiopia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>69</unirecid>
		<iso_code_2>FK</iso_code_2>
		<iso_code_3>FLK</iso_code_3>
		<name>Falkland Islands (Malvinas)</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>70</unirecid>
		<iso_code_2>FO</iso_code_2>
		<iso_code_3>FRO</iso_code_3>
		<name>Faroe Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>71</unirecid>
		<iso_code_2>FJ</iso_code_2>
		<iso_code_3>FJI</iso_code_3>
		<name>Fiji</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>72</unirecid>
		<iso_code_2>FI</iso_code_2>
		<iso_code_3>FIN</iso_code_3>
		<name>Finland</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>73</unirecid>
		<iso_code_2>FR</iso_code_2>
		<iso_code_3>FRA</iso_code_3>
		<name>France</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>74</unirecid>
		<iso_code_2>FX</iso_code_2>
		<iso_code_3>FXX</iso_code_3>
		<name>France, Metropolitan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>75</unirecid>
		<iso_code_2>GF</iso_code_2>
		<iso_code_3>GUF</iso_code_3>
		<name>French Guiana</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>76</unirecid>
		<iso_code_2>PF</iso_code_2>
		<iso_code_3>PYF</iso_code_3>
		<name>French Polynesia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>77</unirecid>
		<iso_code_2>TF</iso_code_2>
		<iso_code_3>ATF</iso_code_3>
		<name>French Southern Territories</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>78</unirecid>
		<iso_code_2>GA</iso_code_2>
		<iso_code_3>GAB</iso_code_3>
		<name>Gabon</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>79</unirecid>
		<iso_code_2>GM</iso_code_2>
		<iso_code_3>GMB</iso_code_3>
		<name>Gambia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>80</unirecid>
		<iso_code_2>GE</iso_code_2>
		<iso_code_3>GEO</iso_code_3>
		<name>Georgia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>81</unirecid>
		<iso_code_2>DE</iso_code_2>
		<iso_code_3>DEU</iso_code_3>
		<name>Germany</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>82</unirecid>
		<iso_code_2>GH</iso_code_2>
		<iso_code_3>GHA</iso_code_3>
		<name>Ghana</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>83</unirecid>
		<iso_code_2>GI</iso_code_2>
		<iso_code_3>GIB</iso_code_3>
		<name>Gibraltar</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>84</unirecid>
		<iso_code_2>GR</iso_code_2>
		<iso_code_3>GRC</iso_code_3>
		<name>Greece</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>85</unirecid>
		<iso_code_2>GL</iso_code_2>
		<iso_code_3>GRL</iso_code_3>
		<name>Greenland</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>86</unirecid>
		<iso_code_2>GD</iso_code_2>
		<iso_code_3>GRD</iso_code_3>
		<name>Grenada</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>87</unirecid>
		<iso_code_2>GP</iso_code_2>
		<iso_code_3>GLP</iso_code_3>
		<name>Guadeloupe</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>88</unirecid>
		<iso_code_2>GU</iso_code_2>
		<iso_code_3>GUM</iso_code_3>
		<name>Guam</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>89</unirecid>
		<iso_code_2>GT</iso_code_2>
		<iso_code_3>GTM</iso_code_3>
		<name>Guatemala</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>90</unirecid>
		<iso_code_2>GN</iso_code_2>
		<iso_code_3>GIN</iso_code_3>
		<name>Guinea</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>91</unirecid>
		<iso_code_2>GW</iso_code_2>
		<iso_code_3>GNB</iso_code_3>
		<name>Guinea-bissau</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>92</unirecid>
		<iso_code_2>GY</iso_code_2>
		<iso_code_3>GUY</iso_code_3>
		<name>Guyana</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>93</unirecid>
		<iso_code_2>HT</iso_code_2>
		<iso_code_3>HTI</iso_code_3>
		<name>Haiti</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>94</unirecid>
		<iso_code_2>HM</iso_code_2>
		<iso_code_3>HMD</iso_code_3>
		<name>Heard and Mc Donald Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>95</unirecid>
		<iso_code_2>HN</iso_code_2>
		<iso_code_3>HND</iso_code_3>
		<name>Honduras</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>96</unirecid>
		<iso_code_2>HK</iso_code_2>
		<iso_code_3>HKG</iso_code_3>
		<name>Hong Kong</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>97</unirecid>
		<iso_code_2>HU</iso_code_2>
		<iso_code_3>HUN</iso_code_3>
		<name>Hungary</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>98</unirecid>
		<iso_code_2>IS</iso_code_2>
		<iso_code_3>ISL</iso_code_3>
		<name>Iceland</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>99</unirecid>
		<iso_code_2>IN</iso_code_2>
		<iso_code_3>IND</iso_code_3>
		<name>India</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>100</unirecid>
		<iso_code_2>ID</iso_code_2>
		<iso_code_3>IDN</iso_code_3>
		<name>Indonesia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>101</unirecid>
		<iso_code_2>IR</iso_code_2>
		<iso_code_3>IRN</iso_code_3>
		<name>Iran (Islamic Republic of)</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>102</unirecid>
		<iso_code_2>IQ</iso_code_2>
		<iso_code_3>IRQ</iso_code_3>
		<name>Iraq</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>103</unirecid>
		<iso_code_2>IE</iso_code_2>
		<iso_code_3>IRL</iso_code_3>
		<name>Ireland</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>104</unirecid>
		<iso_code_2>IL</iso_code_2>
		<iso_code_3>ISR</iso_code_3>
		<name>Israel</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>105</unirecid>
		<iso_code_2>IT</iso_code_2>
		<iso_code_3>ITA</iso_code_3>
		<name>Italy</name>
		<tax>20</tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>106</unirecid>
		<iso_code_2>JM</iso_code_2>
		<iso_code_3>JAM</iso_code_3>
		<name>Jamaica</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>107</unirecid>
		<iso_code_2>JP</iso_code_2>
		<iso_code_3>JPN</iso_code_3>
		<name>Japan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>108</unirecid>
		<iso_code_2>JO</iso_code_2>
		<iso_code_3>JOR</iso_code_3>
		<name>Jordan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>109</unirecid>
		<iso_code_2>KZ</iso_code_2>
		<iso_code_3>KAZ</iso_code_3>
		<name>Kazakhstan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>110</unirecid>
		<iso_code_2>KE</iso_code_2>
		<iso_code_3>KEN</iso_code_3>
		<name>Kenya</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>111</unirecid>
		<iso_code_2>KI</iso_code_2>
		<iso_code_3>KIR</iso_code_3>
		<name>Kiribati</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>112</unirecid>
		<iso_code_2>KP</iso_code_2>
		<iso_code_3>PRK</iso_code_3>
		<name>Korea, Democratic People&#039;s Republic of</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>113</unirecid>
		<iso_code_2>KR</iso_code_2>
		<iso_code_3>KOR</iso_code_3>
		<name>Korea, Republic of</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>114</unirecid>
		<iso_code_2>KW</iso_code_2>
		<iso_code_3>KWT</iso_code_3>
		<name>Kuwait</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>115</unirecid>
		<iso_code_2>KG</iso_code_2>
		<iso_code_3>KGZ</iso_code_3>
		<name>Kyrgyzstan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>116</unirecid>
		<iso_code_2>LA</iso_code_2>
		<iso_code_3>LAO</iso_code_3>
		<name>Lao People&#039;s Democratic Republic</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>117</unirecid>
		<iso_code_2>LV</iso_code_2>
		<iso_code_3>LVA</iso_code_3>
		<name>Latvia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>118</unirecid>
		<iso_code_2>LB</iso_code_2>
		<iso_code_3>LBN</iso_code_3>
		<name>Lebanon</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>119</unirecid>
		<iso_code_2>LS</iso_code_2>
		<iso_code_3>LSO</iso_code_3>
		<name>Lesotho</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>120</unirecid>
		<iso_code_2>LR</iso_code_2>
		<iso_code_3>LBR</iso_code_3>
		<name>Liberia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>121</unirecid>
		<iso_code_2>LY</iso_code_2>
		<iso_code_3>LBY</iso_code_3>
		<name>Libyan Arab Jamahiriya</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>122</unirecid>
		<iso_code_2>LI</iso_code_2>
		<iso_code_3>LIE</iso_code_3>
		<name>Liechtenstein</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>123</unirecid>
		<iso_code_2>LT</iso_code_2>
		<iso_code_3>LTU</iso_code_3>
		<name>Lithuania</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>124</unirecid>
		<iso_code_2>LU</iso_code_2>
		<iso_code_3>LUX</iso_code_3>
		<name>Luxembourg</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>125</unirecid>
		<iso_code_2>MO</iso_code_2>
		<iso_code_3>MAC</iso_code_3>
		<name>Macau</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>126</unirecid>
		<iso_code_2>MK</iso_code_2>
		<iso_code_3>MKD</iso_code_3>
		<name>Macedonia, The Former Yugoslav Republic of</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>127</unirecid>
		<iso_code_2>MG</iso_code_2>
		<iso_code_3>MDG</iso_code_3>
		<name>Madagascar</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>128</unirecid>
		<iso_code_2>MW</iso_code_2>
		<iso_code_3>MWI</iso_code_3>
		<name>Malawi</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>129</unirecid>
		<iso_code_2>MY</iso_code_2>
		<iso_code_3>MYS</iso_code_3>
		<name>Malaysia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>130</unirecid>
		<iso_code_2>MV</iso_code_2>
		<iso_code_3>MDV</iso_code_3>
		<name>Maldives</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>131</unirecid>
		<iso_code_2>ML</iso_code_2>
		<iso_code_3>MLI</iso_code_3>
		<name>Mali</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>132</unirecid>
		<iso_code_2>MT</iso_code_2>
		<iso_code_3>MLT</iso_code_3>
		<name>Malta</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>133</unirecid>
		<iso_code_2>MH</iso_code_2>
		<iso_code_3>MHL</iso_code_3>
		<name>Marshall Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>134</unirecid>
		<iso_code_2>MQ</iso_code_2>
		<iso_code_3>MTQ</iso_code_3>
		<name>Martinique</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>135</unirecid>
		<iso_code_2>MR</iso_code_2>
		<iso_code_3>MRT</iso_code_3>
		<name>Mauritania</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>136</unirecid>
		<iso_code_2>MU</iso_code_2>
		<iso_code_3>MUS</iso_code_3>
		<name>Mauritius</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>137</unirecid>
		<iso_code_2>YT</iso_code_2>
		<iso_code_3>MYT</iso_code_3>
		<name>Mayotte</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>138</unirecid>
		<iso_code_2>MX</iso_code_2>
		<iso_code_3>MEX</iso_code_3>
		<name>Mexico</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>139</unirecid>
		<iso_code_2>FM</iso_code_2>
		<iso_code_3>FSM</iso_code_3>
		<name>Micronesia, Federated States of</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>140</unirecid>
		<iso_code_2>MD</iso_code_2>
		<iso_code_3>MDA</iso_code_3>
		<name>Moldova, Republic of</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>141</unirecid>
		<iso_code_2>MC</iso_code_2>
		<iso_code_3>MCO</iso_code_3>
		<name>Monaco</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>142</unirecid>
		<iso_code_2>MN</iso_code_2>
		<iso_code_3>MNG</iso_code_3>
		<name>Mongolia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>143</unirecid>
		<iso_code_2>MS</iso_code_2>
		<iso_code_3>MSR</iso_code_3>
		<name>Montserrat</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>144</unirecid>
		<iso_code_2>MA</iso_code_2>
		<iso_code_3>MAR</iso_code_3>
		<name>Morocco</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>145</unirecid>
		<iso_code_2>MZ</iso_code_2>
		<iso_code_3>MOZ</iso_code_3>
		<name>Mozambique</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>146</unirecid>
		<iso_code_2>MM</iso_code_2>
		<iso_code_3>MMR</iso_code_3>
		<name>Myanmar</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>147</unirecid>
		<iso_code_2>NA</iso_code_2>
		<iso_code_3>NAM</iso_code_3>
		<name>Namibia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>148</unirecid>
		<iso_code_2>NR</iso_code_2>
		<iso_code_3>NRU</iso_code_3>
		<name>Nauru</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>149</unirecid>
		<iso_code_2>NP</iso_code_2>
		<iso_code_3>NPL</iso_code_3>
		<name>Nepal</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>150</unirecid>
		<iso_code_2>NL</iso_code_2>
		<iso_code_3>NLD</iso_code_3>
		<name>Netherlands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>151</unirecid>
		<iso_code_2>AN</iso_code_2>
		<iso_code_3>ANT</iso_code_3>
		<name>Netherlands Antilles</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>152</unirecid>
		<iso_code_2>NC</iso_code_2>
		<iso_code_3>NCL</iso_code_3>
		<name>New Caledonia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>153</unirecid>
		<iso_code_2>NZ</iso_code_2>
		<iso_code_3>NZL</iso_code_3>
		<name>New Zealand</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>154</unirecid>
		<iso_code_2>NI</iso_code_2>
		<iso_code_3>NIC</iso_code_3>
		<name>Nicaragua</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>155</unirecid>
		<iso_code_2>NE</iso_code_2>
		<iso_code_3>NER</iso_code_3>
		<name>Niger</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>156</unirecid>
		<iso_code_2>NG</iso_code_2>
		<iso_code_3>NGA</iso_code_3>
		<name>Nigeria</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>157</unirecid>
		<iso_code_2>NU</iso_code_2>
		<iso_code_3>NIU</iso_code_3>
		<name>Niue</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>158</unirecid>
		<iso_code_2>NF</iso_code_2>
		<iso_code_3>NFK</iso_code_3>
		<name>Norfolk Island</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>159</unirecid>
		<iso_code_2>MP</iso_code_2>
		<iso_code_3>MNP</iso_code_3>
		<name>Northern Mariana Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>160</unirecid>
		<iso_code_2>NO</iso_code_2>
		<iso_code_3>NOR</iso_code_3>
		<name>Norway</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>161</unirecid>
		<iso_code_2>OM</iso_code_2>
		<iso_code_3>OMN</iso_code_3>
		<name>Oman</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>162</unirecid>
		<iso_code_2>PK</iso_code_2>
		<iso_code_3>PAK</iso_code_3>
		<name>Pakistan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>163</unirecid>
		<iso_code_2>PW</iso_code_2>
		<iso_code_3>PLW</iso_code_3>
		<name>Palau</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>164</unirecid>
		<iso_code_2>PA</iso_code_2>
		<iso_code_3>PAN</iso_code_3>
		<name>Panama</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>165</unirecid>
		<iso_code_2>PG</iso_code_2>
		<iso_code_3>PNG</iso_code_3>
		<name>Papua New Guinea</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>166</unirecid>
		<iso_code_2>PY</iso_code_2>
		<iso_code_3>PRY</iso_code_3>
		<name>Paraguay</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>167</unirecid>
		<iso_code_2>PE</iso_code_2>
		<iso_code_3>PER</iso_code_3>
		<name>Peru</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>168</unirecid>
		<iso_code_2>PH</iso_code_2>
		<iso_code_3>PHL</iso_code_3>
		<name>Philippines</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>169</unirecid>
		<iso_code_2>PN</iso_code_2>
		<iso_code_3>PCN</iso_code_3>
		<name>Pitcairn</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>170</unirecid>
		<iso_code_2>PL</iso_code_2>
		<iso_code_3>POL</iso_code_3>
		<name>Poland</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>171</unirecid>
		<iso_code_2>PT</iso_code_2>
		<iso_code_3>PRT</iso_code_3>
		<name>Portugal</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>172</unirecid>
		<iso_code_2>PR</iso_code_2>
		<iso_code_3>PRI</iso_code_3>
		<name>Puerto Rico</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>173</unirecid>
		<iso_code_2>QA</iso_code_2>
		<iso_code_3>QAT</iso_code_3>
		<name>Qatar</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>174</unirecid>
		<iso_code_2>RE</iso_code_2>
		<iso_code_3>REU</iso_code_3>
		<name>Reunion</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>175</unirecid>
		<iso_code_2>RO</iso_code_2>
		<iso_code_3>ROM</iso_code_3>
		<name>Romania</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>176</unirecid>
		<iso_code_2>RU</iso_code_2>
		<iso_code_3>RUS</iso_code_3>
		<name>Russian Federation</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>177</unirecid>
		<iso_code_2>RW</iso_code_2>
		<iso_code_3>RWA</iso_code_3>
		<name>Rwanda</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>178</unirecid>
		<iso_code_2>KN</iso_code_2>
		<iso_code_3>KNA</iso_code_3>
		<name>Saint Kitts and Nevis</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>179</unirecid>
		<iso_code_2>LC</iso_code_2>
		<iso_code_3>LCA</iso_code_3>
		<name>Saint Lucia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>180</unirecid>
		<iso_code_2>VC</iso_code_2>
		<iso_code_3>VCT</iso_code_3>
		<name>Saint Vincent and the Grenadines</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>181</unirecid>
		<iso_code_2>WS</iso_code_2>
		<iso_code_3>WSM</iso_code_3>
		<name>Samoa</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>182</unirecid>
		<iso_code_2>SM</iso_code_2>
		<iso_code_3>SMR</iso_code_3>
		<name>San Marino</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>183</unirecid>
		<iso_code_2>ST</iso_code_2>
		<iso_code_3>STP</iso_code_3>
		<name>Sao Tome and Principe</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>184</unirecid>
		<iso_code_2>SA</iso_code_2>
		<iso_code_3>SAU</iso_code_3>
		<name>Saudi Arabia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>185</unirecid>
		<iso_code_2>SN</iso_code_2>
		<iso_code_3>SEN</iso_code_3>
		<name>Senegal</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>186</unirecid>
		<iso_code_2>SC</iso_code_2>
		<iso_code_3>SYC</iso_code_3>
		<name>Seychelles</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>187</unirecid>
		<iso_code_2>SL</iso_code_2>
		<iso_code_3>SLE</iso_code_3>
		<name>Sierra Leone</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>188</unirecid>
		<iso_code_2>SG</iso_code_2>
		<iso_code_3>SGP</iso_code_3>
		<name>Singapore</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>189</unirecid>
		<iso_code_2>SK</iso_code_2>
		<iso_code_3>SVK</iso_code_3>
		<name>Slovakia (Slovak Republic)</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>190</unirecid>
		<iso_code_2>SI</iso_code_2>
		<iso_code_3>SVN</iso_code_3>
		<name>Slovenia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>191</unirecid>
		<iso_code_2>SB</iso_code_2>
		<iso_code_3>SLB</iso_code_3>
		<name>Solomon Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>192</unirecid>
		<iso_code_2>SO</iso_code_2>
		<iso_code_3>SOM</iso_code_3>
		<name>Somalia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>193</unirecid>
		<iso_code_2>ZA</iso_code_2>
		<iso_code_3>ZAF</iso_code_3>
		<name>South Africa</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>194</unirecid>
		<iso_code_2>GS</iso_code_2>
		<iso_code_3>SGS</iso_code_3>
		<name>South Georgia and the South Sandwich Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>195</unirecid>
		<iso_code_2>ES</iso_code_2>
		<iso_code_3>ESP</iso_code_3>
		<name>Spain</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>196</unirecid>
		<iso_code_2>LK</iso_code_2>
		<iso_code_3>LKA</iso_code_3>
		<name>Sri Lanka</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>197</unirecid>
		<iso_code_2>SH</iso_code_2>
		<iso_code_3>SHN</iso_code_3>
		<name>St. Helena</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>198</unirecid>
		<iso_code_2>PM</iso_code_2>
		<iso_code_3>SPM</iso_code_3>
		<name>St. Pierre and Miquelon</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>199</unirecid>
		<iso_code_2>SD</iso_code_2>
		<iso_code_3>SDN</iso_code_3>
		<name>Sudan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>200</unirecid>
		<iso_code_2>SR</iso_code_2>
		<iso_code_3>SUR</iso_code_3>
		<name>Suriname</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>201</unirecid>
		<iso_code_2>SJ</iso_code_2>
		<iso_code_3>SJM</iso_code_3>
		<name>Svalbard and Jan Mayen Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>202</unirecid>
		<iso_code_2>SZ</iso_code_2>
		<iso_code_3>SWZ</iso_code_3>
		<name>Swaziland</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>203</unirecid>
		<iso_code_2>SE</iso_code_2>
		<iso_code_3>SWE</iso_code_3>
		<name>Sweden</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>204</unirecid>
		<iso_code_2>CH</iso_code_2>
		<iso_code_3>CHE</iso_code_3>
		<name>Switzerland</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>205</unirecid>
		<iso_code_2>SY</iso_code_2>
		<iso_code_3>SYR</iso_code_3>
		<name>Syrian Arab Republic</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>206</unirecid>
		<iso_code_2>TW</iso_code_2>
		<iso_code_3>TWN</iso_code_3>
		<name>Taiwan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>207</unirecid>
		<iso_code_2>TJ</iso_code_2>
		<iso_code_3>TJK</iso_code_3>
		<name>Tajikistan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>208</unirecid>
		<iso_code_2>TZ</iso_code_2>
		<iso_code_3>TZA</iso_code_3>
		<name>Tanzania, United Republic of</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>209</unirecid>
		<iso_code_2>TH</iso_code_2>
		<iso_code_3>THA</iso_code_3>
		<name>Thailand</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>210</unirecid>
		<iso_code_2>TG</iso_code_2>
		<iso_code_3>TGO</iso_code_3>
		<name>Togo</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>211</unirecid>
		<iso_code_2>TK</iso_code_2>
		<iso_code_3>TKL</iso_code_3>
		<name>Tokelau</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>212</unirecid>
		<iso_code_2>TO</iso_code_2>
		<iso_code_3>TON</iso_code_3>
		<name>Tonga</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>213</unirecid>
		<iso_code_2>TT</iso_code_2>
		<iso_code_3>TTO</iso_code_3>
		<name>Trinidad and Tobago</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>214</unirecid>
		<iso_code_2>TN</iso_code_2>
		<iso_code_3>TUN</iso_code_3>
		<name>Tunisia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>215</unirecid>
		<iso_code_2>TR</iso_code_2>
		<iso_code_3>TUR</iso_code_3>
		<name>Turkey</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>216</unirecid>
		<iso_code_2>TM</iso_code_2>
		<iso_code_3>TKM</iso_code_3>
		<name>Turkmenistan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>217</unirecid>
		<iso_code_2>TC</iso_code_2>
		<iso_code_3>TCA</iso_code_3>
		<name>Turks and Caicos Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>218</unirecid>
		<iso_code_2>TV</iso_code_2>
		<iso_code_3>TUV</iso_code_3>
		<name>Tuvalu</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>219</unirecid>
		<iso_code_2>UG</iso_code_2>
		<iso_code_3>UGA</iso_code_3>
		<name>Uganda</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>220</unirecid>
		<iso_code_2>UA</iso_code_2>
		<iso_code_3>UKR</iso_code_3>
		<name>Ukraine</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>221</unirecid>
		<iso_code_2>AE</iso_code_2>
		<iso_code_3>ARE</iso_code_3>
		<name>United Arab Emirates</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>222</unirecid>
		<iso_code_2>GB</iso_code_2>
		<iso_code_3>GBR</iso_code_3>
		<name>United Kingdom</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>223</unirecid>
		<iso_code_2>US</iso_code_2>
		<iso_code_3>USA</iso_code_3>
		<name>United States</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>224</unirecid>
		<iso_code_2>UM</iso_code_2>
		<iso_code_3>UMI</iso_code_3>
		<name>United States Minor Outlying Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>225</unirecid>
		<iso_code_2>UY</iso_code_2>
		<iso_code_3>URY</iso_code_3>
		<name>Uruguay</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>226</unirecid>
		<iso_code_2>UZ</iso_code_2>
		<iso_code_3>UZB</iso_code_3>
		<name>Uzbekistan</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>227</unirecid>
		<iso_code_2>VU</iso_code_2>
		<iso_code_3>VUT</iso_code_3>
		<name>Vanuatu</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>228</unirecid>
		<iso_code_2>VA</iso_code_2>
		<iso_code_3>VAT</iso_code_3>
		<name>Vatican City State (Holy See)</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>229</unirecid>
		<iso_code_2>VE</iso_code_2>
		<iso_code_3>VEN</iso_code_3>
		<name>Venezuela</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>230</unirecid>
		<iso_code_2>VN</iso_code_2>
		<iso_code_3>VNM</iso_code_3>
		<name>Viet Nam</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>231</unirecid>
		<iso_code_2>VG</iso_code_2>
		<iso_code_3>VGB</iso_code_3>
		<name>Virgin Islands (British)</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>232</unirecid>
		<iso_code_2>VI</iso_code_2>
		<iso_code_3>VIR</iso_code_3>
		<name>Virgin Islands (U.S.)</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>233</unirecid>
		<iso_code_2>WF</iso_code_2>
		<iso_code_3>WLF</iso_code_3>
		<name>Wallis and Futuna Islands</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>234</unirecid>
		<iso_code_2>EH</iso_code_2>
		<iso_code_3>ESH</iso_code_3>
		<name>Western Sahara</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>235</unirecid>
		<iso_code_2>YE</iso_code_2>
		<iso_code_3>YEM</iso_code_3>
		<name>Yemen</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>236</unirecid>
		<iso_code_2>YU</iso_code_2>
		<iso_code_3>YUG</iso_code_3>
		<name>Yugoslavia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>237</unirecid>
		<iso_code_2>ZR</iso_code_2>
		<iso_code_3>ZAR</iso_code_3>
		<name>Zaire</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>238</unirecid>
		<iso_code_2>ZM</iso_code_2>
		<iso_code_3>ZMB</iso_code_3>
		<name>Zambia</name>
		<tax></tax>
	</fnc_countries>
	<fnc_countries>
		<unirecid>239</unirecid>
		<iso_code_2>ZW</iso_code_2>
		<iso_code_3>ZWE</iso_code_3>
		<name>Zimbabwe</name>
		<tax></tax>
	</fnc_countries>
</fndatabase>