<?php exit(0);?>
		<tables>
			<field>
				<name>unirecid</name>
				<primarykey>1</primarykey>
				<extra>autoincrement</extra>
				<frm_show>0</frm_show>
			</field>
		<field>
			<name>category</name>
		</field>
		<field>
			<name>product</name>
		</field>
	<indexfield>category</indexfield>
<!--
	<driver>mysql</driver>
	<host>localhost</host>
	<user>root</user>
	<password>root</password>
	<usecachefile><usecachefile>
-->
</tables>
