<?php exit(0);?>
<tables>
	<field>
		<name>unirecid</name>
		<primarykey>1</primarykey>
		<extra>autoincrement</extra>
		<frm_show>0</frm_show>
	</field>
	<field>
		<name>order_id</name>
	</field>	
	<field>
		<name>name</name>
	</field>
	<field>
		<name>qta</name>
	</field>	
	<field>
		<name>pid</name>
	</field>
	<field>
		<name>price</name>
	</field>	
</tables>