<?php exit(0);?>
		<tables>
			<field>
				<name>unirecid</name>
				<primarykey>1</primarykey>
				<extra>autoincrement</extra>
				<frm_show>0</frm_show>
			</field>
			<field>
				<name>name</name>
				<frm_required>1</frm_required>
			</field>
			<field>
				<name>url</name>
			</field>
			<field>
				<name>description</name>
				<frm_cols>80</frm_cols>
				<frm_rows>10</frm_rows>
				<frm_help_it>Inserisci qui la descrizione</frm_help_it>
				<frm_help_en>Insert description here</frm_help_en>
				<frm_it>Descrizione</frm_it>
				<frm_en>Description</frm_en>
				<type>text</type>
				<frm_type>html</frm_type>
				<frm_multilanguages>auto</frm_multilanguages>
			</field>
				<field>
		<name>sort_order</name>
		<frm_it>Posizione</frm_it>
		<frm_en>Position</frm_en>
	</field>
			
			<field>
					<name>photo1</name>
					<frm_it>Immagine</frm_it>
					<frm_en>Image</frm_en>
					<frm_showinlist>1</frm_showinlist>
					<thumb_listheight>64</thumb_listheight>
					<type>image</type>
					<thumbsize>64</thumbsize>
					<view_tag>center</view_tag>
			</field>
		
<field>
		<name>description_en</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
<field>
		<name>description_es</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
<field>
		<name>description_de</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
<field>
		<name>description_fr</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
<field>
		<name>description_it</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
</tables>
