<?php exit(0);?>
<tables>
	<field>
		<name>unirecid</name>
		<primarykey>1</primarykey>
		<extra>autoincrement</extra>
		<frm_show>0</frm_show>
	</field>
	<field>
		<name>title</name>
		<frm_required>1</frm_required>
	</field>
	<field>
		<name>text</name>
		<frm_cols>80</frm_cols>
		<frm_rows>10</frm_rows>
		<type>text</type>
		<frm_type>html</frm_type>
		<frm_multilanguages>auto</frm_multilanguages>
	</field>
	<field>
		<name>sort_order</name>
	</field>
	
<field>
		<name>text_en</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
<field>
		<name>text_es</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
<field>
		<name>text_de</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
<field>
		<name>text_fr</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
<field>
		<name>text_it</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
<field>
		<name>text_ru</name>
		<type>text</type>
		<frm_multilanguage>1</frm_multilanguage>
	</field>
</tables>
