<?xml version="1.0" encoding="UTF-8"?>
<?php exit(0);?>
<fndatabase>
	<fncf_fncommerce>
		<varname>currency</varname>
		<varvalue>EUR</varvalue>
		<defaultvalue>EUR</defaultvalue>
	</fncf_fncommerce>
	<fncf_fncommerce>
		<varname>currency_symbol</varname>
		<varvalue>&amp;euro;</varvalue>
		<defaultvalue>&amp;euro;</defaultvalue>
	</fncf_fncommerce>
	<fncf_fncommerce>
		<varname>show_categories_tree_check</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fncf_fncommerce>
	<fncf_fncommerce>
		<varname>show_categories_tree</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fncf_fncommerce>
	<fncf_fncommerce>
		<varname>show_ranges</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fncf_fncommerce>
	<fncf_fncommerce>
		<varname>fnc_sort_product</varname>
		<varvalue>sort_order</varvalue>
		<defaultvalue>sort_order</defaultvalue>
	</fncf_fncommerce>
	<fncf_fncommerce>
		<varname>fnc_nothumbs</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_fncommerce>
	<fncf_fncommerce>
		<varname>fnc_enable_recipient</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_fncommerce>
	<fncf_fncommerce>
		<varname>fnc_only_catalog</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fncf_fncommerce>
	<fncf_fncommerce>
		<varname>fnc_show_prices</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_fncommerce>
</fndatabase>