<?xml version="1.0" encoding="UTF-8"?>
<?php exit(0);?>
<fndatabase>
	<fn_settings>
		<varname>use_urlserverpath</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>sitename</varname>
		<varvalue>Finis</varvalue>
		<defaultvalue>Finis</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>site_title</varname>
		<varvalue>Finis CMS</varvalue>
		<defaultvalue>Finis CMS</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>site_subtitle</varname>
		<varvalue>f.i.n.i.s.</varvalue>
		<defaultvalue>f.i.n.i.s.</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>keywords</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>languages</varname>
		<varvalue>en</varvalue>
		<defaultvalue>en</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>theme</varname>
		<varvalue>default</varvalue>
		<defaultvalue>default</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>controlcenter_theme</varname>
		<varvalue>classic</varvalue>
		<defaultvalue>classic</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>switchtheme</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>siteurl</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>site_email_address</varname>
		<varvalue>nobody@site_email_address.set</varvalue>
		<defaultvalue>nobody@site_email_address.set</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>log_email_address</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_compress_gzip</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>home_section</varname>
		<varvalue>home</varvalue>
		<defaultvalue>home</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>jet_lag</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>showaccesskey</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_log_email</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_mod_rewrite</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>links_mode</varname>
		<varvalue>html</varvalue>
		<defaultvalue>html</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_registration</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>username_is_email</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>registration_by_email</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>remember_login</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_captcha</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>htmleditor</varname>
		<varvalue>ckeditor4</varvalue>
		<defaultvalue>ckeditor4</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_online_administration</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>credits</varname>
		<varvalue>Powered by Finis</varvalue>
		<defaultvalue>Powered by Finis</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>maintenance</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>url_update</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>use_cache</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>timezone</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fn_settings>
</fndatabase>