<?xml version="1.0" encoding="UTF-8"?>
<?php exit(0);?>
<fndatabase>
	<fn_sections>
		<id>home</id>
		<type></type>
		<parent></parent>
		<position>0</position>
		<title>Home</title>
		<description></description>
		<startdate></startdate>
		<enddate></enddate>
		<status>1</status>
		<hidden></hidden>
		<accesskey></accesskey>
		<keywords></keywords>
		<sectionpath>sections</sectionpath>
		<level></level>
		<group_view></group_view>
		<group_edit></group_edit>
		<blocksmode></blocksmode>
		<blocks></blocks>
	</fn_sections>
	<fn_sections>
		<id>login</id>
		<type>login</type>
		<parent></parent>
		<position>20</position>
		<title>Login</title>
		<description></description>
		<startdate></startdate>
		<enddate></enddate>
		<status>1</status>
		<hidden>0</hidden>
		<accesskey></accesskey>
		<keywords></keywords>
		<sectionpath>sections</sectionpath>
		<level></level>
		<group_view></group_view>
		<group_edit></group_edit>
		<blocksmode>hide</blocksmode>
		<blocks>user</blocks>
	</fn_sections>
	<fn_sections>
		<id>search</id>
		<type>search</type>
		<parent></parent>
		<position>30</position>
		<title>Search</title>
		<description></description>
		<startdate></startdate>
		<enddate></enddate>
		<status>1</status>
		<hidden>0</hidden>
		<accesskey></accesskey>
		<keywords></keywords>
		<sectionpath>sections</sectionpath>
		<level></level>
		<group_view></group_view>
		<group_edit></group_edit>
		<blocksmode></blocksmode>
		<blocks></blocks>
	</fn_sections>
	<fn_sections>
		<id>sitemap</id>
		<type>sitemap_tree</type>
		<parent></parent>
		<position>40</position>
		<title>Site Map</title>
		<description></description>
		<startdate></startdate>
		<enddate></enddate>
		<status>1</status>
		<hidden>0</hidden>
		<accesskey></accesskey>
		<keywords></keywords>
		<sectionpath>sections</sectionpath>
		<level></level>
		<group_view></group_view>
		<group_edit></group_edit>
		<blocksmode></blocksmode>
		<blocks></blocks>
	</fn_sections>
</fndatabase>