<?xml version="1.0" encoding="UTF-8"?>
<?php exit(0);?>
<fndatabase>
	<fncf_home>
		<varname>databasename</varname>
		<varvalue>fndatabase</varvalue>
		<defaultvalue>fndatabase</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>recordsperpage</varname>
		<varvalue>12</varvalue>
		<defaultvalue>12</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>groupinsert</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>groupadmin</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>groupview</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>mailalert</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>viewonlycreator</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>generate_googlesitemap</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>tables</varname>
		<varvalue>fn_files</varvalue>
		<defaultvalue>fn_files</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>search_orders</varname>
		<varvalue>title,recordinsert,recordupdate</varvalue>
		<defaultvalue>title,recordinsert,recordupdate</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>defaultorder</varname>
		<varvalue>recordupdate</varvalue>
		<defaultvalue>recordupdate</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>enable_comments_notify</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>search_min</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>titlefield</varname>
		<varvalue>title</varvalue>
		<defaultvalue>title</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>descriptionfield</varname>
		<varvalue>description</varvalue>
		<defaultvalue>description</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>search_options</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>navigate_groups</varname>
		<varvalue>username</varvalue>
		<defaultvalue>username</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>search_partfields</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>search_fields</varname>
		<varvalue>username</varvalue>
		<defaultvalue>username</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>appendquery</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>image_titlefield</varname>
		<varvalue>photo1</varvalue>
		<defaultvalue>photo1</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>image_size</varname>
		<varvalue>400</varvalue>
		<defaultvalue>400</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>image_size_h</varname>
		<varvalue>300</varvalue>
		<defaultvalue>300</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>table_rules</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>enable_permissions_each_records</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>enable_permissions_edit_each_records</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>permissions_records_groups</varname>
		<varvalue>dbview_rw,dbview_ro</varvalue>
		<defaultvalue>dbview_rw,dbview_ro</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>permissions_records_edit_groups</varname>
		<varvalue>dbview_rw,dbview_ro</varvalue>
		<defaultvalue>dbview_rw,dbview_ro</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>enable_history</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>enable_export</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>enable_delete</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>hide_on_delete</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>default_show_groups</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>enable_statistics</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>search_query_native_mysql</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>enable_offlineform</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>documents_folder</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fncf_home>
	<fncf_home>
		<varname>enable_cache</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fncf_home>
	
</fndatabase>