<?php exit(0);?>
<fndatabase>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>1</unirecid>
    <weight>500</weight>
    <price>11.64</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>2</unirecid>
    <weight>1000</weight>
    <price>15.09</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>3</unirecid>
    <weight>1500</weight>
    <price>19.41</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>4</unirecid>
    <weight>2000</weight>
    <price>23.72</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>5</unirecid>
    <weight>2500</weight>
    <price>28.04</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>6</unirecid>
    <weight>3000</weight>
    <price>30.09</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>7</unirecid>
    <weight>3500</weight>
    <price>32.04</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>8</unirecid>
    <weight>4000</weight>
    <price>33.99</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>9</unirecid>
    <weight>4500</weight>
    <price>35.94</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>10</unirecid>
    <weight>5000</weight>
    <price>37.89</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>11</unirecid>
    <weight>5500</weight>
    <price>38.89</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>12</unirecid>
    <weight>6000</weight>
    <price>39.88</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>13</unirecid>
    <weight>6500</weight>
    <price>40.88</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>14</unirecid>
    <weight>7000</weight>
    <price>41.88</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>15</unirecid>
    <weight>7500</weight>
    <price>42.88</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>16</unirecid>
    <weight>8000</weight>
    <price>43.88</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>17</unirecid>
    <weight>8500</weight>
    <price>44.88</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>18</unirecid>
    <weight>9000</weight>
    <price>45.87</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>19</unirecid>
    <weight>9500</weight>
    <price>46.87</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>20</unirecid>
    <weight>10000</weight>
    <price>47.87</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>21</unirecid>
    <weight>11000</weight>
    <price>51.46</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>22</unirecid>
    <weight>12000</weight>
    <price>55.05</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>23</unirecid>
    <weight>13000</weight>
    <price>58.64</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>24</unirecid>
    <weight>14000</weight>
    <price>62.22</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>25</unirecid>
    <weight>15000</weight>
    <price>65.91</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>26</unirecid>
    <weight>16000</weight>
    <price>69.4</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>27</unirecid>
    <weight>17000</weight>
    <price>72.99</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>28</unirecid>
    <weight>18000</weight>
    <price>76.58</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>29</unirecid>
    <weight>19000</weight>
    <price>80.16</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>30</unirecid>
    <weight>20000</weight>
    <price>83.75</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>31</unirecid>
    <weight>21000</weight>
    <price>87.1</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>32</unirecid>
    <weight>22000</weight>
    <price>90.45</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>33</unirecid>
    <weight>23000</weight>
    <price>93.8</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>34</unirecid>
    <weight>24000</weight>
    <price>97.15</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>35</unirecid>
    <weight>25000</weight>
    <price>100.5</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>36</unirecid>
    <weight>26000</weight>
    <price>102.77</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>37</unirecid>
    <weight>27000</weight>
    <price>105.05</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>38</unirecid>
    <weight>28000</weight>
    <price>107.33</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>39</unirecid>
    <weight>29000</weight>
    <price>109.61</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>40</unirecid>
    <weight>30000</weight>
    <price>111.88</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>41</unirecid>
    <weight>35000</weight>
    <price>123.27</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>42</unirecid>
    <weight>40000</weight>
    <price>134.66</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>43</unirecid>
    <weight>45000</weight>
    <price>146.05</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>44</unirecid>
    <weight>50000</weight>
    <price>157.44</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>45</unirecid>
    <weight>55000</weight>
    <price>171.58</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>46</unirecid>
    <weight>60000</weight>
    <price>185.72</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>47</unirecid>
    <weight>65000</weight>
    <price>199.87</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>48</unirecid>
    <weight>70000</weight>
    <price>214.01</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>49</unirecid>
    <weight>80000</weight>
    <price>242.3</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>50</unirecid>
    <weight>90000</weight>
    <price>270.59</price>
  </fnc_shippingcosts_DHL_Estero>
  <fnc_shippingcosts_DHL_Estero>
    <unirecid>51</unirecid>
    <weight>100000</weight>
    <price>298.88</price>
  </fnc_shippingcosts_DHL_Estero>
</fndatabase>
