<?php exit(0);?>
<fndatabase>
	<fnc_zones>
		<unirecid>130</unirecid>
		<country>195</country>
		<code>A Coru&ntilde;a</code>
		<name>A Coru&ntilde;a</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>131</unirecid>
		<country>195</country>
		<code>Alava</code>
		<name>Alava</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>132</unirecid>
		<country>195</country>
		<code>Albacete</code>
		<name>Albacete</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>133</unirecid>
		<country>195</country>
		<code>Alicante</code>
		<name>Alicante</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>134</unirecid>
		<country>195</country>
		<code>Almeria</code>
		<name>Almeria</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>135</unirecid>
		<country>195</country>
		<code>Asturias</code>
		<name>Asturias</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>136</unirecid>
		<country>195</country>
		<code>Avila</code>
		<name>Avila</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>137</unirecid>
		<country>195</country>
		<code>Badajoz</code>
		<name>Badajoz</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>138</unirecid>
		<country>195</country>
		<code>Baleares</code>
		<name>Baleares</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>139</unirecid>
		<country>195</country>
		<code>Barcelona</code>
		<name>Barcelona</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>140</unirecid>
		<country>195</country>
		<code>Burgos</code>
		<name>Burgos</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>141</unirecid>
		<country>195</country>
		<code>Caceres</code>
		<name>Caceres</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>142</unirecid>
		<country>195</country>
		<code>Cadiz</code>
		<name>Cadiz</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>143</unirecid>
		<country>195</country>
		<code>Cantabria</code>
		<name>Cantabria</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>144</unirecid>
		<country>195</country>
		<code>Castellon</code>
		<name>Castellon</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>145</unirecid>
		<country>195</country>
		<code>Ceuta</code>
		<name>Ceuta</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>146</unirecid>
		<country>195</country>
		<code>Ciudad Real</code>
		<name>Ciudad Real</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>147</unirecid>
		<country>195</country>
		<code>Cordoba</code>
		<name>Cordoba</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>148</unirecid>
		<country>195</country>
		<code>Cuenca</code>
		<name>Cuenca</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>149</unirecid>
		<country>195</country>
		<code>Girona</code>
		<name>Girona</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>150</unirecid>
		<country>195</country>
		<code>Granada</code>
		<name>Granada</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>151</unirecid>
		<country>195</country>
		<code>Guadalajara</code>
		<name>Guadalajara</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>152</unirecid>
		<country>195</country>
		<code>Guipuzcoa</code>
		<name>Guipuzcoa</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>153</unirecid>
		<country>195</country>
		<code>Huelva</code>
		<name>Huelva</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>154</unirecid>
		<country>195</country>
		<code>Huesca</code>
		<name>Huesca</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>155</unirecid>
		<country>195</country>
		<code>Jaen</code>
		<name>Jaen</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>156</unirecid>
		<country>195</country>
		<code>La Rioja</code>
		<name>La Rioja</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>157</unirecid>
		<country>195</country>
		<code>Las Palmas</code>
		<name>Las Palmas</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>158</unirecid>
		<country>195</country>
		<code>Leon</code>
		<name>Leon</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>159</unirecid>
		<country>195</country>
		<code>Lleida</code>
		<name>Lleida</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>160</unirecid>
		<country>195</country>
		<code>Lugo</code>
		<name>Lugo</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>161</unirecid>
		<country>195</country>
		<code>Madrid</code>
		<name>Madrid</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>162</unirecid>
		<country>195</country>
		<code>Malaga</code>
		<name>Malaga</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>163</unirecid>
		<country>195</country>
		<code>Melilla</code>
		<name>Melilla</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>164</unirecid>
		<country>195</country>
		<code>Murcia</code>
		<name>Murcia</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>165</unirecid>
		<country>195</country>
		<code>Navarra</code>
		<name>Navarra</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>166</unirecid>
		<country>195</country>
		<code>Ourense</code>
		<name>Ourense</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>167</unirecid>
		<country>195</country>
		<code>Palencia</code>
		<name>Palencia</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>168</unirecid>
		<country>195</country>
		<code>Pontevedra</code>
		<name>Pontevedra</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>169</unirecid>
		<country>195</country>
		<code>Salamanca</code>
		<name>Salamanca</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>170</unirecid>
		<country>195</country>
		<code>Santa Cruz de Tenerife</code>
		<name>Santa Cruz de Tenerife</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>171</unirecid>
		<country>195</country>
		<code>Segovia</code>
		<name>Segovia</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>172</unirecid>
		<country>195</country>
		<code>Sevilla</code>
		<name>Sevilla</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>173</unirecid>
		<country>195</country>
		<code>Soria</code>
		<name>Soria</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>174</unirecid>
		<country>195</country>
		<code>Tarragona</code>
		<name>Tarragona</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>175</unirecid>
		<country>195</country>
		<code>Teruel</code>
		<name>Teruel</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>176</unirecid>
		<country>195</country>
		<code>Toledo</code>
		<name>Toledo</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>177</unirecid>
		<country>195</country>
		<code>Valencia</code>
		<name>Valencia</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>178</unirecid>
		<country>195</country>
		<code>Valladolid</code>
		<name>Valladolid</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>179</unirecid>
		<country>195</country>
		<code>Vizcaya</code>
		<name>Vizcaya</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>180</unirecid>
		<country>195</country>
		<code>Zamora</code>
		<name>Zamora</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>181</unirecid>
		<country>195</country>
		<code>Zaragoza</code>
		<name>Zaragoza</name>
	</fnc_zones>
</fndatabase>