<?php exit(0);?>
<fndatabase>
	<fnc_zones>
		<unirecid>79</unirecid>
		<country>81</country>
		<code>NDS</code>
		<name>Niedersachsen</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>80</unirecid>
		<country>81</country>
		<code>BAW</code>
		<name>Baden-W&uuml;rttemberg</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>81</unirecid>
		<country>81</country>
		<code>BAY</code>
		<name>Bayern</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>82</unirecid>
		<country>81</country>
		<code>BER</code>
		<name>Berlin</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>83</unirecid>
		<country>81</country>
		<code>BRG</code>
		<name>Brandenburg</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>84</unirecid>
		<country>81</country>
		<code>BRE</code>
		<name>Bremen</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>85</unirecid>
		<country>81</country>
		<code>HAM</code>
		<name>Hamburg</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>86</unirecid>
		<country>81</country>
		<code>HES</code>
		<name>Hessen</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>87</unirecid>
		<country>81</country>
		<code>MEC</code>
		<name>Mecklenburg-Vorpommern</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>88</unirecid>
		<country>81</country>
		<code>NRW</code>
		<name>Nordrhein-Westfalen</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>89</unirecid>
		<country>81</country>
		<code>RHE</code>
		<name>Rheinland-Pfalz</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>90</unirecid>
		<country>81</country>
		<code>SAR</code>
		<name>Saarland</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>91</unirecid>
		<country>81</country>
		<code>SAS</code>
		<name>Sachsen</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>92</unirecid>
		<country>81</country>
		<code>SAC</code>
		<name>Sachsen-Anhalt</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>93</unirecid>
		<country>81</country>
		<code>SCN</code>
		<name>Schleswig-Holstein</name>
	</fnc_zones>
	<fnc_zones>
		<unirecid>94</unirecid>
		<country>81</country>
		<code>THE</code>
		<name>Th&uuml;ringen</name>
	</fnc_zones>
</fndatabase>